version: '3.9'

services:
  mongo:
    container_name: mongo_container
    image: 'mongo'
    volumes:
      - mongo-data:/data/db
    networks:
      - qr-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --bind_ip_all
    restart: always

  cache:
    container_name: cache_container
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - qr-net

  backend:
    container_name: backend_container
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - cache
    environment:
      PORT: ${PORT}
      MONGO_DB_URI: ${MONGO_DB_URI}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
      JWT_EXPIRY: ${JWT_EXPIRY}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - qr-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/www.qrcode.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/www.qrcode.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/www.qrcode.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/www.qrcode.uxlivinglab.online/privkey.pem:ro
    restart: always
    networks:
      - qr-net
    depends_on:
      - backend

volumes:
  mongo-data:
  cache:

networks:
  qr-net:
    driver: bridge
