version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - qr-net
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
    networks:
      - qr-net
    restart: unless-stopped

  mongo:
    container_name: mongo_container
    image: 'mongo'
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - qr-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --bind_ip_all
    restart: always

  cache:
    container_name: cache_container
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: bash -c "echo 1 > /proc/sys/vm/overcommit_memory && redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - cache:/data
    networks:
      - qr-net
    privileged: true

  backend:
    container_name: backend_container
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - cache
      - kafka
    environment:
      PORT: ${PORT}
      MONGO_DB_URI: ${MONGO_DB_URI}
      MONGO_SCAN_URI: ${MONGO_SCAN_URI}
      MONGO_DB_NAME: ${MONGO_SCAN_DB}
      MONGO_EXHIBITOR_COLL: ${MONGO_EXHIBITOR_COLL}
      MONGO_TOKEN_COLL: ${MONGO_TOKEN_COLL}
      DATABASE_ID: ${DATABASE_ID}
      DATACUBE_API_KEY: ${DATACUBE_API_KEY}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_BROKER: ${KAFKA_BROKER}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY}
      JWT_EXPIRY: ${JWT_EXPIRY}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - qr-net

  consumer:
      build:
        context: ./consumer
        dockerfile: Dockerfile
      environment:
        NODE_ENV: ${NODE_ENV}
        KAFKA_BROKER: ${KAFKA_BROKER}
        KAFKA_TOPIC: ${KAFKA_TOPIC}
        KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
        MONGO_URI: ${MONGO_SCAN_URI}
        MONGO_DB_NAME: ${MONGO_SCAN_DB}
        MONGO_EXHIBITOR_COLL: ${MONGO_EXHIBITOR_COLL}
        DATACUBE_API_KEY: ${DATACUBE_API_KEY}
        DATABASE_ID: ${DATABASE_ID}
      depends_on:
        - kafka
        - mongo
      networks:
        - qr-net
      restart: unless-stopped
  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - qr-net
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/www.qrcode.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/www.qrcode.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/www.qrcode.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/www.qrcode.uxlivinglab.online/privkey.pem:ro
    restart: always
    networks:
      - qr-net
    depends_on:
      - backend


volumes:
  mongo-data:
  cache:

networks:
  qr-net:
    driver: bridge
